# This file is autogenerated; see release/restate.rb.tmpl

class Restate < Formula
  version '0.5.1'
  desc "Restate CLI"
  homepage "https://github.com/restatedev/restate"

  arch = Hardware::CPU.arch.to_s
  if OS.mac?
      if Hardware::CPU.arm?
          url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.aarch64-apple-darwin.tar.gz"
          sha256 "4f2d43051870b457f291e03f36d170f7e7cf4251e342a063294146d28e9eca75"
      else
          url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.x86_64-apple-darwin.tar.gz"
          sha256 "be3882a840eca33d70144b140ee10579079a856c4f3b6092b222afc9daf6867f"
      end
  elsif OS.linux?
     if Hardware::CPU.arm?
         url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.aarch64-unknown-linux-gnu.tar.gz"
         sha256 "8521ab77bd91a7b535e3de506c1ccf99c802a8529e5d271c28b75a7209298b35"
     else
         url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.x86_64-unknown-linux-gnu.tar.gz"
         sha256 "7db4e5d509d180105b24115f073e809e9bdf79ed0d14b9c6155a948d8678838f"
     end
  end

  def install
    bin.install "restate"
  end

  test do
    shell_output("restate -V")
  end
end
