# This file is autogenerated; see release/restate.rb.tmpl

class Restate < Formula
  version '0.7.1'
  desc "Restate CLI"
  homepage "https://github.com/restatedev/restate"

  arch = Hardware::CPU.arch.to_s
  if OS.mac?
      if Hardware::CPU.arm?
          url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.aarch64-apple-darwin.tar.gz"
          sha256 "aac46597d6f6a9ebe29d6f005647e057962d8154ed90b3c388c9e9567725238b"
      else
          url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.x86_64-apple-darwin.tar.gz"
          sha256 "9959dbaaac572a5346c06861d0685f6938fb45ce3b3a96bd57da6ffbb56880db"
      end
  elsif OS.linux?
     if Hardware::CPU.arm?
         url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.aarch64-unknown-linux-musl.tar.gz"
         sha256 "e4b2a573b996967bf8cdd765321d3100e43b0177cdd288f29c3dbc78d37b63e8"
     else
         url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.x86_64-unknown-linux-musl.tar.gz"
         sha256 "8239b149b366c5001a009b9fdb90fc618ad39beffa9e256d5f2395da65e38c54"
     end
  end

  def install
    bin.install "restate"
  end

  test do
    shell_output("restate -V")
  end
end
