# This file is autogenerated; see release/restate.rb.tmpl

class RestateServer < Formula
  version '1.1.4'
  desc "Restate Server"
  homepage "https://github.com/restatedev/restate"

  arch = Hardware::CPU.arch.to_s
  if OS.mac?
      if Hardware::CPU.arm?
          url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.aarch64-apple-darwin.tar.gz"
          sha256 "eae25171e65c73bbe64df60b102c8492943d0a16dc091e73ad7f42affb506ce9"
      else
          url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.x86_64-apple-darwin.tar.gz"
          sha256 "df5ea6c78f476540f087935b6b47b8de0f084cd9db7e039466a603ca9e2b5130"
      end
  elsif OS.linux?
     if Hardware::CPU.arm?
         url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.aarch64-unknown-linux-musl.tar.gz"
         sha256 "55486d93a23ac5c54fa859d4a2f5943db52c867363336830223de16255bfe101"
     else
         url "https://github.com/restatedev/restate/releases/download/v#{version}/restate.x86_64-unknown-linux-musl.tar.gz"
         sha256 "7c53b4d27946b964c99f498eb9c98a1279bfa4ce43d7f6b1dd1136d4dfe90718"
     end
  end

  def install
    bin.install "restate-server"
  end

  test do
    shell_output("restate-server -V")
  end
end
